### ISSUE TITLE
如何繁化網站文件

### ISSUE THREAD

**Issue by gnora3360** [flier268/ConvertZZ#1]
如題目
如何繁化網站文件
只能知道能繁化所有檔案名稱
請問一下要如何繁體化該資料夾內的所有html　CSS JS PHP （包含子資料夾裡面的文件）等等
像是ConvertZ那樣

**Comment by flier268** [comment]
在懸浮球上右鍵->"文件/檔名轉換"->瀏覽
選取到資料夾，不要選取任何檔案，維持檔案名稱欄位為"　"(一個全形空白)，按"開啟"
如果還是沒東西，請檢查篩選器
