### ISSUE TITLE
關於特定單字轉換的問題

### ISSUE THREAD

**Issue by eienmirimu** [flier268/ConvertZZ#11]
作者你好~

我有一個關於特定單字轉換的問題

- 不管是程式預設值的狀態下
- 或是從 Dictionary.csv 字典檔裡面多新增這一行
True	Other	岩	0	岩	0

ConvertZZ 還是會把 "岩" 給簡轉繁為 "巖"

請問要怎麼設定
才可以保持 "岩" <--簡轉繁--> "岩" 這個單字呢?

謝謝~

**Comment by flier268** [comment]
更細的說明在wiki有寫
把優先度調高就好了
True Other 岩 1 岩 0

**Comment by eienmirimu** [comment]
> 更細的說明在wiki有寫
> 把優先度調高就好了
> True Other 岩 1 岩 0

作者你好~

有新增 True Other 岩 1 岩 0 的設定

但是 簡轉繁 似乎還是會把 岩 強制轉換為 巖

https://i.imgur.com/3N4G83m.png

不知道是不是程式內的轉換編碼優先於字典檔的關係呢?

**Comment by flier268** [comment]
我發現了，岩轉換成巖似乎是系統轉的
字典先替換完，再用系統的簡轉繁去轉換
所以就算把岩的優先度調高也沒用
可能要加入保留字的功能
像是優先度>999則加入保留字之類的

**Comment by flier268** [comment]
以添加於 0ed327fba473bb5e207427c5232a142ccc0d8c14

**Comment by flier268** [comment]
有解決你的問題了嗎？

**Comment by eienmirimu** [comment]
抱歉回覆晚了~

1.0.0.8版本 已解決問題  ;)

感謝你~
