### ISSUE TITLE
奇怪的UI設計邏輯

### ISSUE THREAD

**Issue by allentsou** [flier268/ConvertZZ#13]
一個簡單的需求，只是要將簡體檔名轉成繁體，我確按了半天不知道該怎麼執行，
如下圖....，我選好了，按鈕卻出現停止中......
https://imgur.com/8fPboSF
然後下一步要怎麼做???

**Comment by allentsou** [comment]
然後那個藍色懸浮圓球要幹嘛???可以拖曳文件進去嗎?試過卻不行..........
按右鍵的GBK>BIG5、BIG5>GBK作用在哪???真是搞不懂....

**Comment by flier268** [comment]
你所選的不是改文件名稱的，那個是改文件內容的(像是txt,str,ass等檔案)
![image](https://user-images.githubusercontent.com/19989232/62909968-4a9a5480-bdb1-11e9-9d08-9cf2cfeb8193.png)
紅圈圈起來的那個才是
由於你選錯模式，但又選了音樂文件，然後又按了轉換，所以要等他真的停止才能繼續

> 一個簡單的需求，只是要將簡體檔名轉成繁體，我確按了半天不知道該怎麼執行，
> 如下圖....，我選好了，按鈕卻出現停止中......
> https://imgur.com/8fPboSF
> 然後下一步要怎麼做???

**Comment by flier268** [comment]
> 然後那個藍色懸浮圓球要幹嘛???可以拖曳文件進去嗎?試過卻不行..........
> 按右鍵的GBK>BIG5、BIG5>GBK作用在哪???真是搞不懂....

拖曳文件那個有打算設計，但還沒真的做
右鍵的那幾個轉換，都是轉換剪貼簿內容的文字
也許有時間需要來寫一點說明文件

**Comment by flier268** [comment]
請問這有解決你的問題了嗎?
