### ISSUE TITLE
建議支援透過 Chocolatey 安裝

### ISSUE THREAD

**Issue by RJHsiao** [flier268/ConvertZZ#14]
純粹只是個建議，畢竟不是程式本身的改善，也需要另外花時間處理

[Chocolatey 官網](https://chocolatey.org/)
[維基百科 Chocolatey 條目](https://zh.wikipedia.org/wiki/Chocolatey)
[建立 Chocolatey package 的文件](https://chocolatey.org/docs/create-packages)

**Comment by flier268** [comment]
剛剛有測試了一下，安裝Chocolatey需要用指令安裝，他本身也比較少人知道
然後解除安裝的部分也有問題，並不會真的解除安裝

**Comment by RJHsiao** [comment]
Chocolatey 大概只有 power user 以上的人才會去用就是...就是那些會在 Windows 上尋求像 Linux 一樣管理套件的方式來管理應用程式的人(像我)

> 然後解除安裝的部分也有問題

是說解除安裝 Chocolatey？還是解除安裝透過 Chocolatey 安裝的程式？
前者我不知道，後面應該是會把程式本身移除

**Comment by flier268** [comment]
我測試了Firefox，但卻沒有真的解除安裝
由於我個人並沒有這樣的需求，所以暫時不打算支援Chocolatey
但歡迎pull request，我會希望有人與我一同開法
感謝你讓我知道，原來Windows有一個像Ubuntu的商店的東西
