### ISSUE TITLE
ID3 還是有項目無法轉為繁體

### ISSUE THREAD

**Issue by chourete** [flier268/ConvertZZ#15]
https://i.imgur.com/qNQPT8N.png
舉例如圖 在預覽中 演出者 鄧麗君有正確的翻成繁體
但是輸出的時候還是簡體，已經試了好幾次

我有打包我的這些音樂檔 請確認看看
https://drive.google.com/file/d/18k2zYhb6O9xEZF8p-J7fig12f-jtC8Mk/view?usp=sharing

**Comment by flier268** [comment]
你的這個問題我改好了： 51a87ec89f23c38c457fbb3b8c9c7741d729b2df
原因在於Tag的屬性沒有set，因此不如我的預期一般被修改
