### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by allenk** [flier268/ConvertZZ#19]
太晚知道。做得很好！
Buy you a coffee! Please keep going!

(Oops, your PayPal doesn't seem to work, can you try to fix it? It says I don't have the right to pay...)

**Comment by flier268** [comment]
![image](https://user-images.githubusercontent.com/19989232/65487437-78f36f80-ded9-11e9-9298-16e7729cf2d8.png)
被台灣的法令禁止了

**Comment by allenk** [comment]
原來如此啊。不過跨外交易好像可以。
是不是考慮多放幾個支付方式呢？

**Comment by flier268** [comment]
那些第三方支付，其實我都很少在用，有什麼推薦的嗎?

**Comment by allenk** [comment]
其實好像還蠻多的。
比方，智付通 ECPAY綠界科技 等等。不過其實我覺得Line Pay 與 街口 也可以的。

https://medium.com/@evonneyifangtsai/%E5%A6%82%E4%BD%95%E7%94%A8%E8%A1%97%E5%8F%A3%E6%94%AF%E4%BB%98%E5%B0%8F%E9%A1%8D%E6%94%AF%E6%8C%81%E4%BD%9C%E5%AE%B6-4462325afd59

參考這篇看看！

**Comment by flier268** [comment]
加入了街口支付
不過其實我也不抱有人donate的期望，只是放著而已，Paypal只是現有的
聽到你說要donate其實我還滿訝異的

**Comment by flier268** [comment]
如果沒有其他問題，我將關閉此issue

**Comment by allenk** [comment]
Thanks.

Donate 蠻普遍的。我會嘗試用街口donate。
讓我請您喝杯咖啡吧！

flier268 <notifications@github.com> 於 2020年1月4日 週六 18:29 寫道：

**Comment by flier268** [comment]
感謝您的支持
