### ISSUE TITLE
添加功能推薦

### ISSUE THREAD

**Issue by shiuanyue** [flier268/ConvertZZ#2]
能不能添加舊版的詞彙修正? 
 有時會想要自訂一些詞彙修正

**Comment by flier268** [comment]
目前沒有畫UI讓使用者定義，不過可以去Dictionary資料夾看，你可以自己新增，只要副檔名一樣就可以了，只是格式要正確
簡體,繁體

**Comment by flier268** [comment]
已添加於1.0.0.7
操作方法已寫在(wiki)[https://github.com/flier268/ConvertZZ/wiki/%E7%B7%A8%E4%BF%AE%E8%A9%9E%E5%BD%99%E4%BF%AE%E6%AD%A3%E5%AD%97%E5%85%B8]
