### ISSUE TITLE
API 隱私問題

### ISSUE THREAD

**Issue by fekfoq259** [flier268/ConvertZZ#28]
有選項可以選擇不使用聯網的 API 嗎？
[繁化姬的後端可能會留存您所提供的文本與使用者設定，以做為改進轉換正確率的用途。
](https://docs.zhconvert.org/license/)

**Comment by nightcat54** [comment]
很需要 command line

**Comment by SiongSng** [comment]
![圖片](https://user-images.githubusercontent.com/48402225/110229010-00ebfe80-7f41-11eb-9b4d-98bd04494ce0.png)
不是原本就有選項可以選擇了?

**Comment by fekfoq259** [comment]
> 
> 
> ![圖片](https://user-images.githubusercontent.com/48402225/110229010-00ebfe80-7f41-11eb-9b4d-98bd04494ce0.png)
> 不是原本就有選項可以選擇了?

我下載最新的 Release 沒看到「使用本地字典、使用繁化姬API」這個選項。

**Comment by SiongSng** [comment]
因為我是下載原始碼下來編譯的xd

**Comment by SiongSng** [comment]
@fekfoq259 這問題感覺可以關閉了?

**Comment by fekfoq259** [comment]
> 
> 
> @fekfoq259 這問題感覺可以關閉了?

謝謝回覆。編譯的版本確實有這個選項。
