### ISSUE TITLE
能否像原本 ConvertZ 以命令列方式批次執行程式

### ISSUE THREAD

**Issue by ccfang** [flier268/ConvertZZ#3]
例如原本 ConvertZ 可以這樣批次執行：`ConvertZ.exe /i:utf8 /o:utf8 /f:s XXX.txt`

**Comment by flier268** [comment]
原來ConvertZ有這個功能，這我倒是不知道，我會再看看，應該是不難，只是要定義好

**Comment by flier268** [comment]
a6c4b17f9ca818a9310b02e3dcf3bbee5ce41564 已添加該功能

**Comment by flier268** [comment]
如果沒有問題，我將關閉這個issue

**Comment by ccfang** [comment]
感謝提供此功能，不過這邊測試結果似乎有問題，參考看看 :relaxed:

原本檔案為 Big5
![convertzz-issues-3-01](https://user-images.githubusercontent.com/1438603/51455702-bc637000-1d85-11e9-9571-b0f4de29c760.png)

使用命令列方式轉換後
![convertzz-issues-3-02](https://user-images.githubusercontent.com/1438603/51455716-cbe2b900-1d85-11e9-93f3-a6e0ff0ce9ed.png)

![convertzz-issues-3-03](https://user-images.githubusercontent.com/1438603/51455720-d00ed680-1d85-11e9-8d92-3c45ec87ae14.png)

使用原本 ConvertZ 轉換後
![convertzz-issues-3-04](https://user-images.githubusercontent.com/1438603/51455737-e6b52d80-1d85-11e9-9017-82904d415f30.png)

![convertzz-issues-3-05](https://user-images.githubusercontent.com/1438603/51455740-eb79e180-1d85-11e9-853c-3f8bdf52b3ed.png)

**Comment by ccfang** [comment]
測試 OK，轉換結果跟 ConvertZ 一樣，謝謝 :blush:

**Comment by nightcat54** [comment]
請參考
http://fw-william.blogspot.com/2013/12/convertz-command-line.html
