### ISSUE TITLE
沒有轉碼進度

### ISSUE THREAD

**Issue by vb69jm52** [flier268/ConvertZZ#4]
感謝再開發ConvertZ，沒有遇過GB碼.TXT & .MP3是很難感受到這種痛苦的。
1.右上關閉鍵有時比較不方便
2.轉碼沒有進度表和暫停&取消鍵，出錯無法取消。
3.請問有字碼偵測功能嗎，可以所多不同字碼的文字檔全部轉成UTF8

**Comment by flier268** [comment]
1.右上角關閉鍵是什麼意思?
2.這個我會找時間再改
3.編碼偵測這個比較難，只能用推測的(例如GBK常用字的出現次數跟BIG5常用字出現次數去做比較)，目前只能做到GBK跟BIG5判斷，其他的編碼就有點難了，也不一定準確

**Comment by vb69jm52** [comment]
1.軟體關閉鍵，右上角有☒❎，
Ctrl + W 	關閉使用中視窗。
Alt + F4   關閉分頁。
這樣可加速開關。
4.希望有UTF8剪貼簿互轉快速鍵或小視窗。
5.開始時漂浮球的位置，可停留在關閉的位置。

**Comment by vb69jm52** [comment]
6.軟體無法設定關閉同時重覆執行，這套軟體一般不會有同時開啟2個ConvertZZ的需求，假如誤觸變成要再關一次軟體。

**Comment by flier268** [comment]
圈取的文字轉成UTF-8繁體 Google一下是你自己畫的?

**Comment by vb69jm52** [comment]
Google
圈取的文字轉成UTF-8繁體G一下
圈取的文字轉成UTF-8簡體G一下

百度
圈取的文字轉成UTF-8繁體百一下
圈取的文字轉成UTF-8簡體百一下

另存新檔
圈取的文字轉成UTF-8繁體另存...
圈取的文字轉成UTF-8簡體另存...

**Comment by vb69jm52** [comment]
轉碼完成提醒，要還要按確認太過麻煩。
建議可以改成5秒自動關閉的提醒氣泡，或是 咚! 一聲 音效提醒。

**Comment by flier268** [comment]
工作列上的捷徑要有快速選單可以做到，但這是以後的事了(還要添加新的設定頁面，因為把所有選項都放進去也不現實)
但是在Chrome出現選單就需要寫擴充元件了，但這我不熟
有一部分功能已添加a5295c4025e1d1f5b4090b1027ea7ba3fb77551f b0a8f5d4b596bff11c6bab771ace93cbc33920ff 8886481935100aab616a6fc8616e9eed36e3496f e1c2004955422009bd6f26943618e53378d9942a

**Comment by flier268** [comment]
額外的問題請另開Issue，由於原要求以解決，我將關閉此Issue
