### ISSUE TITLE
charset 沒有跟著轉換

### ISSUE THREAD

**Issue by zeteticl** [flier268/ConvertZZ#7]
ConvertZ 會把HTML meta  標籤中的charset  自動轉換
ConvertZZ沒有進行這步驟,實際使用時, HTML會亂碼.

**Comment by zeteticl** [comment]
我指檔案啊
html,htm檔沒有轉換啊
結果我用 notepad++ 手動ctrl +h 轉換🤦🏻

**Comment by zeteticl** [comment]
轉換前
![image](https://user-images.githubusercontent.com/23254376/54250572-5de59180-457f-11e9-9e2e-6ca8790ae9a1.png)

轉換後
![image](https://user-images.githubusercontent.com/23254376/54250650-92594d80-457f-11e9-8fac-7623ce90b86b.png)
![image](https://user-images.githubusercontent.com/23254376/54250664-a43af080-457f-11e9-9605-ca5201641d92.png)


因為還是UTF-8 所以會顯示亂碼
試了ConvertZZ_v1.0.0.6 還是一樣

**Comment by zeteticl** [comment]
另外
詞彙修正好像也沒有成功
EG 战斗 =>戰斗
而不是
战斗 => 戰鬥

**Comment by flier268** [comment]
詞彙修正這樣算是成功的，那是因為簡體字缺少太多資訊了，一個字可能取代了很多的字，我只能用取代的方式轉換，試問如果是你人工判斷，你要如何判定這邊應該是EG戰斗而不是EG戰鬥呢？畢竟戰鬥比較常出現不是？

**Comment by zeteticl** [comment]
對不起 Flier268 大大,
詞彙修正那裡我是誤會了.應該是我設定上出錯

**Comment by flier268** [comment]
charset沒轉換是因為網頁的內容是
charset=utf-8">
但應該要打charset="utf-8">
你少個雙引號

**Comment by zeteticl** [comment]
content="text/html; charset=utf-8"
是合法的, 只是html 4 的表達方式
沒少打" , 這是content 的內容

而且我不是轉換自己的網頁啊. 不是我少打(哭了

**Comment by zeteticl** [comment]
更正一下問題
content="text/html; charset=utf-8"
在ConvertZ 會轉換
在ConvertZZ不會轉換

**Comment by flier268** [comment]
commit ff48a75a4e6b985c92ed17349639ffd939b1c477

**Comment by zeteticl** [comment]
感謝
