### ISSUE TITLE
希望增加標點符號 半形>全形 轉換功能

### ISSUE THREAD

**Issue by siumonmon** [flier268/ConvertZZ#8]
希望在設定裡增加選項
剪貼轉換標點符號 半形>全形 功能
文件轉換標點符號 半形>全形 功能
謝謝

**Comment by flier268** [comment]
半形>全形轉換有沒有一個對照表之類的呢?
因為我自己不需要用到這個功能，所以可能需要由你提供一個表來指定要怎麼轉

**Comment by siumonmon** [comment]
常用符號
,=，
~=～
!=！
#=＃
$=＄
%=％
^=︿
&=＆
*=＊
-=－
+=＋
{=｛
}=｝
;=；
|=｜
?=？
(=（
)=）
“=「
”=」
‘=『
’=』
[=［
]=］
{=｛
}=｝
...=…
·=．
 =　空格


下面可能對修改HTML出現問題
:=：
.=。
"=、
@=＠
<=＜
>=＞
==＝

**Comment by siumonmon** [comment]
線上全形半形轉換程式
http://www.taiwanad.com/tool_convertpunct.php

**Comment by jfcherng** [comment]
把英文的標點也轉為全形的話是比較奇怪的。

**Comment by flier268** [comment]
已添加於 28d5a0fb20b16af7a3fa7c0d4a8867b80dbbe58b
