### ISSUE TITLE
無法正確繁轉簡

### ISSUE THREAD

**Issue by dasu88** [flier268/ConvertZZ#9]
今日使用，繁體轉簡體皆成亂碼，不知為何?
環境為 windows 10 1903
![2019-05-06_184831](https://user-images.githubusercontent.com/23251263/57220956-d02e9b80-702f-11e9-8fcd-0b95b0c33084.jpg)

**Comment by flier268** [comment]
看起來很正常啊
你目前所選的設定是把Big5轉GBK，通常用於簡體系統出現亂碼時，將亂碼轉成簡體字
你想要把「測試」轉「测试」嗎？

**Comment by dasu88** [comment]
謝謝說明…不過這個邏輯我不大懂，明明來源是big5，怎會是選擇UTF-8?
我單純只是要把剪貼簿來源的繁體big5轉為簡體GBK，ConvertZZ的操作似乎沒有ConvertZ來得直覺，在ConvertZ裡，只要點擊一個按鍵就把剪貼簿裡的繁體文字轉為簡體字了，依您的說明，ConvertZZ共要點擊三處才能達到此需求…

再以直接轉換為例，無論我選擇哪一種轉換，都無法得到正確的簡體文字…
![2019-05-07_081144](https://user-images.githubusercontent.com/23251263/57262781-3bb05180-70a0-11e9-85ea-5253811a09ad.jpg)

**Comment by flier268** [comment]
怎麼跟你說呢？你的Windows系統裡面，其實混雜著UTF8跟Big5兩種編碼，雖然看起來都一樣，但其實兩者不同。

繁體系統看到亂碼，就是因為GBK的字被當作Big5看了，這時候就需要再它反過來，把Big5當GBK看，才換變成可以辨識的字，也就是在Big5裡面，依照GBK的號碼，去找對應的字

以「繁」舉例：
* 「繁」這個字，在GBK的編號為0xB7B1，如果去Big5面找0xB7B1，則會得到「楛」這個字，這個動作就是「Big5>GBK」
* 「楛」這個字，在Big5的編號為0xB7B1，如果去GBK面找0xB7B1，則會得到「繁」這個字，這個動作就是「GBK>Big5」

不知道這樣解釋，你清楚我在講什麼了嗎?(其實我自己有時候都會搞混...)

但其實呢，你網頁上看到的，無論是「繁」還是「楛」其實都是UTF-8啦！根本就不是Big5(感覺亂七八糟的對吧！)

另外，右鍵選單或快捷鍵那個才是剪貼簿轉換，你開的這個頁面是給需要更進階功能的使用者用的，大部分人都只需要剪貼簿轉換就夠了

**Comment by flier268** [comment]
順帶一提，你把ConvertZ跟ConvertZZ比較，不知道你有沒有發現兩者轉出來的結果有時會不同呢?
有時候並不是我的ConvertZZ寫錯喔～因為ConvertZ有的轉碼真的轉錯了，明顯的例子就是Html code跟Unicode轉換，照理說應該要可以互轉的，但實際上不行

**Comment by dasu88** [comment]
很感謝你花了這麼多時間回覆。
我目前的操作都還是在windows 系統的記事本轉換而非網頁，理論上…未經unicode存檔，記事本都應該都還是在big5編碼模式…這是我的認知，所以才會對於來源選擇UTF-8而非big5 大腦有些打結…
因為我一直都是使用ConvertZ，才轉換ConvertZZ不久，所以有些操作邏輯與習慣都還維持在原來的狀態，持續摸索ConvertZZ中，謝謝你提供了這個好工具

**Comment by flier268** [comment]
沒錯，筆記本用ANSI在繁體中文的Windows就是Big5(在簡體的則為GBK)，如果你用Big5 > Big5也有一部分可以，但有很多簡體字在Big5內是找不到的，所以會出現一些問題

**Comment by flier268** [comment]
請問你的問題有都解決了嗎？

**Comment by dasu88** [comment]
是的，是操作方式的差異，非ConvertZZ的問題
